# Generated by Django 2.1.7 on 2019-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bank_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('national_id', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('uace_uce_slip', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('cv', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('recommendation', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('lc', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('applied_at', models.CharField(blank=True, max_length=50)),
                ('applied_from', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bank_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('national_id', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('uace_uce_slip', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('cv', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('recommendation', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('lc', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('applied_at', models.CharField(blank=True, max_length=50)),
                ('applied_from', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyGenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theFile', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('firebase_id_token', models.CharField(max_length=50)),
            ],
        ),
    ]
